#!/bin/sh

urlencode() {
echo ${1// /"%20"}
}

url='https://bh4d9od16a-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20vanilla%20JavaScript%20(lite)%203.30.0%3Bdocsearch.js%202.6.3&x-algolia-application-id=BH4D9OD16A&x-algolia-api-key=3df93446658cd9c4e314d4c02a052188'

function query () {
  curl $url \
    -s \
    -H 'Connection: keep-alive' \
    -H 'accept: application/json' \
    -H 'content-type: application/x-www-form-urlencoded' \
    --data "{\"requests\":[{\"indexName\":\"tailwindcss\",\"params\":\"query=$(urlencode $@)&hitsPerPage=10&facetFilters=%5B%22version%3Av1%22%5D\"}]}" \
    --compressed &
}
res=$(jq -r '.results[0].hits[] | "\(.hierarchy.lvl0) > \(.hierarchy.lvl1) > \(.url)"' <<< "$(query $@)")
echo "$res"
